global:
  cattle:
    systemDefaultRegistry: ""
  kubectl:
    repository: rancher/kubectl
    tag: v1.20.2
    pullPolicy: IfNotPresent
  imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
pluginServer:
  image:
    repository: /ui-extension-extensions-api-demo
    pullPolicy: Always
    tag: 0.1.0
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  deployment:
    replicas: 1
  resources: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
plugin:
  enabled: true
  versionOverride: ""
  noCache: false
