name: Build Dashboard (Branch)
on:
  push:
    branches:
      - 'release-2.7*'
      - '*-dev'
      - richard-cox-2.7.patch1-drone

jobs:
  build-validation:
    name: Build Test
    uses: ./.github/workflows/build-test.yaml
  build:
    name: Build and Upload
    uses: ./.github/workflows/build-and-upload.yaml
    needs:
      - build-validation
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      CI_BRANCH: ${{github.ref_name}}
