name: check-plugins-build
on:
  pull_request:
    branches:
      - master
env:
  TEST_PERSIST_BUILD: true
jobs:
  validate:
    # Resource starved when running in container, so run in non-container runner
    runs-on: runs-on,runner=8cpu-linux-x64,run-id=${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Validate Plugin build system
        run: ./shell/scripts/test-plugins-build.sh
        shell: bash

      - name: Upload files
        uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: test
          path: |
            /tmp/tmp.**/test-app
            !/tmp/tmp.**/test-app/dist/js/*.map
            !/tmp/tmp.**/test-app/node_modules/
            !/tmp/tmp.**/test-app/pkg/test-pkg/node_modules/
          retention-days: 2
