name: Build and Publish Rancher Components

on:
  push:
    tags:
        - 'components-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org'
        scope: '@rancher'

    - name: Install
      run: yarn install:ci

    - name: Lint
      run: yarn lint:lib

    - name: Build
      run: yarn build:lib

    - name: Unit Test
      run: yarn test:ci ./pkg/rancher-components

    - name: Publish to npm
      run: |
        echo "$GITHUB_REF_NAME"
        if [[ $GITHUB_REF_NAME == components-v*alpha.* ]]; then
          yarn publish:lib --tag alpha
        elif [[ $GITHUB_REF_NAME == components-v*beta.* ]]; then
          yarn publish:lib --tag beta
        else
          yarn publish:lib
        fi
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
