name: storybook
on:
  push:
    paths:
      - 'storybook/**/*'
      - 'pkg/rancher-components/**/*'
      - 'shell/components/**/*'
      - 'shell/assets/**/*'
      - 'shell/utils/**/*'
      - 'shell/directives/**/*'
      - 'shell/config/**/*'
      - 'shell/composables/**/*'
    branches:
      - master
  pull_request:
    paths:
      - 'storybook/**/*'
      - 'pkg/rancher-components/**/*'
      - 'shell/components/**/*'
      - 'shell/assets/**/*'
      - 'shell/utils/**/*'
      - 'shell/directives/**/*'
      - 'shell/config/**/*'
      - 'shell/composables/**/*'
    branches:
      - master
jobs:
  storybook:
    container: registry.suse.com/bci/nodejs:20
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    steps:
    - uses: actions/checkout@v5
    - name: Setup Node
      uses: ./.github/actions/setup-node
    - name: Install packages
      run: yarn install
    - name: Build Storybook
      run: |
        yarn build-storybook
    - name: Publish Storybook
      if: ${{ github.event_name == 'push' && github.repository_owner == 'rancher'}}
      env:
        STORYBOOK_TOKEN: ${{ secrets.STORYBOOK_TOKEN }}
      run: .github/workflows/scripts/publish-storybook
