name: Validate Pull Request

on:
  pull_request:
    types: [opened, edited, synchronize, milestoned, demilestoned]

jobs:
  validate-description:
    name: Description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Validate description checklist has been completed
        if: ${{ ! contains(github.event.pull_request.labels.*.name, 'area/dependencies') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.url }}
        run: ./.github/workflows/scripts/pr-check-checklist.sh

  validate-branch-milestone:
    name: Branch Milestone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        # We only need to fetch the file on the default branch (where it usually lives)
        # to ensure we get the latest configuration file.
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 1

      - name: Check PR Milestone against Branch Config
        run: ./.github/workflows/scripts/pr-check-milestone.sh